---
# Bring up db tier (redis, mongodb).
- hosts: "{{ deploy_env }}-tsuru-db"
  sudo: yes
  roles:
    - bennojoy.redis

- hosts: "{{ deploy_env }}-tsuru-db"
  sudo: yes
  sudo_user: root
  roles:
    - greendayonfire.mongodb

# tsuru core components.
- hosts: "{{ deploy_env }}-tsuru-gandalf*"
  sudo: yes
  roles:
    - gandalf

- hosts: "{{ deploy_env }}-tsuru-router*"
  sudo: yes
  roles:
    - hipache

- hosts: "{{ deploy_env }}-tsuru-api*"
  sudo: yes
  roles:
    - role: tsuru_api
      tags: tsuru_api

- hosts: "{{ deploy_env }}-tsuru-api*"
  sudo: yes
  tasks:
    - name: add admin team
      run_once: true
      shell: >
        mongo tsuru --eval 'db.teams.update({_id: "admin"}, {_id: "admin"}, {upsert: true})';
      delegate_to: "{{ mongodb_host }}"

    - name: add admin user to admin team
      run_once: true
      shell: >
        mongo tsuru --eval "db.teams.update({_id: 'admin'}, {\$addToSet: {users: '{{admin_user}}'}})";
      delegate_to: "{{ mongodb_host }}"

# TODO : handle the case where the user already exists
    - name: add admin user
      run_once: true
      shell: >
        curl -sS -XPOST -d"{\"email\":\"{{admin_user}}\",\"password\":\"{{admin_password}}\"}" "http://127.0.0.1:{{api_port}}/users"

    - name: login with the admin user
      run_once: true
      shell: >
        token=$(curl -sS -XPOST -d"{\"password\":\"{{admin_password}}\"}" "http://127.0.0.1:{{api_port}}/users/{{admin_user}}/tokens" | jq -r .token);
        echo "${token}" > ~/.tsuru_token

- hosts: "{{ deploy_env }}-tsuru-gandalf*"
  sudo: yes
  tasks:
    - name: generate tsuru token
      run_once: true
      shell: tsr token
      delegate_to: "{{ tsuru_api_internal_lb }}"
      register: tsr_token

    - name: write tsuru token to .bash_profile
      lineinfile:
        state: present
        dest: /home/git/.bash_profile
        regexp: export TSURU_TOKEN=
        line: export TSURU_TOKEN={{ tsr_token.stdout }}

    - name: restart gandalf
      service: name=gandalf-server state=restarted

- hosts: "{{ deploy_env }}-tsuru-docker*"
  sudo: yes
  roles:
    - docker_server

  post_tasks:
    - name: Register node.
      shell: >
        tsuru-admin docker-node-add --register address=http://{{ gce_private_ip }}:{{ docker_port }}
      delegate_to: "{{ tsuru_api_internal_lb }}"
      when: ip_field == "gce_private_ip"
    - name: Register node.
      shell: >
        tsuru-admin docker-node-add --register address=http://{{ gce_private_ip }}:{{ docker_port }}
      delegate_to: "{{ tsuru_api_internal_lb }}"
      when: ip_field == "ec2_private_ip_address"

- include: postgres.yml
- include: ssl-proxy.yml
