# Bring up db tier (redis, mongodb).
- hosts: "{{ hosts_prefix }}-tsuru-db"
  sudo: yes
  roles:
    - bennojoy.redis

- hosts: "{{ hosts_prefix }}-tsuru-db"
  sudo: yes
  sudo_user: root
  roles:
    - greendayonfire.mongodb

# tsuru core components.
- hosts: "{{ hosts_prefix }}-tsuru-gandalf*"
  sudo: yes
  roles:
    - gandalf

- include: tsuru_api.yml

- hosts: "{{ hosts_prefix }}-tsuru-gandalf*"
  sudo: yes
  tasks:
    - name: generate tsuru token
      run_once: true
      shell: tsr token
      delegate_to: "{{ tsuru_api_host }}"
      register: tsr_token

    - name: write tsuru token to .bash_profile
      lineinfile:
        state: present
        dest: /home/git/.bash_profile
        regexp: export TSURU_TOKEN=
        line: export TSURU_TOKEN={{ tsr_token.stdout }}

    - name: restart gandalf
      service: name=gandalf-server state=restarted

- hosts: "{{ hosts_prefix }}-tsuru-docker*"
  sudo: yes
  roles:
    - docker_server

  post_tasks:
    - name: Register node.
      shell: >
        tsuru-admin docker-node-add --register address=http://{{ gce_private_ip }}:{{ docker_port }} pool=default
      delegate_to: "{{ tsuru_api_host }}"
      when: gce_private_ip is defined
    - name: Register node.
      shell: >
        tsuru-admin docker-node-add --register address=http://{{ ec2_private_ip_address }}:{{ docker_port }} pool=default
      delegate_to: "{{ tsuru_api_host }}"
      when: ec2_private_ip_address is defined
    - name: Check docker nodes are in the default pool
      shell: >
        tsuru-admin docker-node-list -f pool=default
      delegate_to: "{{ tsuru_api_host }}"
      register: docker_node_list
    - name: Update docker node metadata for default pool (AWS)
      shell: >
        tsuru-admin docker-node-update http://{{ ec2_private_ip_address }}:{{ docker_port }} pool=default
      delegate_to: "{{ tsuru_api_host }}"
      when: "ec2_private_ip_address is defined and not ec2_private_ip_address in docker_node_list.stdout"
    - name: Update docker node metadata for default pool (GCE)
      shell: >
        tsuru-admin docker-node-update http://{{ gce_private_ip }}:{{ docker_port }} pool=default
      delegate_to: "{{ tsuru_api_host }}"
      when: "gce_private_ip is defined and not gce_private_ip in docker_node_list.stdout"


- include: postgres.yml
- include: router.yml
