- hosts: "{{ hosts_prefix }}-influx-grafana*"
  sudo: yes
  vars:
    influxdb_version: 0.9.4.2
  roles:
    - role: influxdb
    - role: Stouts.grafana
  post_tasks:
    - name: Copy grafana API control script
      copy: src=files/datasource.sh dest=/usr/local/bin/datasource.sh mode=0750 owner=root group=root
    - name: Add influx datasource to grafana
      shell: /usr/local/bin/datasource.sh {{ influxdb_database }}

- hosts: "{{ hosts_prefix }}-*:!{{ hosts_prefix}}-tsuru-coreos-docker-*"
  sudo: yes
  tags: telegraf
  vars:
  pre_tasks:
    - set_fact: host_tag_name="{{ ec2_tag_Name }}"
      when: "platform == 'aws'"
    - set_fact: host_tag_name="{{ gce_name }}"
      when: "platform == 'gce'"
  roles:
    - role: telegraf
      telegraf_version: 0.2.0
      influxdb_tags:
        job: "{{ host_tag_name }}"
        host_ip: "{{ ansible_default_ipv4.address }}"

