- hosts: "{{ hosts_prefix }}-tsuru-influx-grafana*"
  sudo: yes
  tags: influx
  vars:
    influxdb_version: 0.9.4.2
  roles:
    - role: influxdb
    - role: Stouts.grafana
  post_tasks:
    - name: Copy grafana API control script
      copy: src=files/datasource.sh dest=/usr/local/bin/datasource.sh mode=0750 owner=root group=root
    - name: Add influx datasource to grafana
      shell: /usr/local/bin/datasource.sh {{ influxdb_database }}
    - name: Copy grafana API dashboard files
      copy: src=files/{{ item }} dest=/root/{{ item }} mode=0750 owner=root group=root
      with_items:
         - grafana-lib.sh
         - grafana-upload-dashboard.sh
         - tsuru-dashboard.json
    - name: Upload Tsuru dashboard
      shell: /bin/bash grafana-upload-dashboard.sh tsuru-dashboard.json
      args:
        chdir: /root/

- hosts: "{{ hosts_prefix }}-*:!{{ hosts_prefix}}-tsuru-coreos-docker-*"
  sudo: yes
  tags: telegraf
  vars:
  pre_tasks:
    - set_fact: instance_name="{{ ec2_tag_Name }}"
      when: "platform == 'aws'"
    - set_fact: instance_name="{{ gce_name }}"
      when: "platform == 'gce'"
    # Note: instance_type must be set as a fact. Using this expression directly in
    # the role variable resulted in a weird character not parseable by telegraf (???)
    - set_fact: instance_type="{{ instance_name | regex_replace('.*-tsuru-(.*[^0-9])(-[0-9]+)?$', '\\1') }}"
  roles:
    - role: telegraf
      telegraf_version: 0.2.0
      influxdb_tags:
        instance_name: "{{ instance_name }}"
        type: "{{ instance_type }}"
        host_ip: "{{ ansible_default_ipv4.address }}"

