- hosts: "{{ hosts_prefix }}-influx-grafana*"
  sudo: yes
  vars:
    influxdb_version: 0.9.1
  roles:
    - role: influxdb
    - role: Stouts.grafana
  tasks:
    - include: "firewall/influx-grafana.yml"
  post_tasks:
    - name: Copy grafana API control script
      copy: src=files/datasource.sh dest=/usr/local/bin/datasource.sh mode=0750 owner=root group=root
    - name: Add influx datasource to grafana
      shell: /usr/local/bin/datasource.sh {{ influxdb_database }}

- hosts: "{{ hosts_prefix }}-*"
  sudo: yes
  tags: telegraf
  vars:
    telegraf_version: 0.1.4
  roles:
    - telegraf
