- hosts: "{{ hosts_prefix }}-influx-grafana*"
  sudo: yes
  vars:
    influxdb_version: 0.9.1
    telegraf_version: 0.1.4
  pre_tasks:
    # FIXME: Remove when deployed everywhere.
    - name: Remove custom /etc/default/telegraf hack
      file: path=/etc/default/telegraf state=absent
  roles:
    - role: influxdb
    - role: telegraf
    - role: Stouts.grafana
  post_tasks:
    - name: Copy grafana API control script
      copy: src=files/datasource.sh dest=/usr/local/bin/datasource.sh mode=0750 owner=root group=root
    - name: Add influx datasource to grafana
      shell: /usr/local/bin/datasource.sh {{ influxdb_database }}

- hosts: "{{ hosts_prefix }}-*"
  sudo: yes
  roles:
    - telegraf
