---
- hosts: "{{ hosts_prefix }}-tsuru-postgres-*"
  sudo: yes
  sudo_user: root
  vars_files:
    - "postgres_common.yml"

  pre_tasks:
    - include_vars: postgres_master.yml
      when: "ansible_default_ipv4.address == postgres_master"

  roles:
    - ANXS.postgresql
    - { role: wal_e, when: enable_postgres_log_shipping is defined and enable_postgres_log_shipping }

  post_tasks:
    - include: postgres_master_post.yml
      when: "ansible_default_ipv4.address == postgres_master"
    - include: postgres_standby.yml
      when: "ansible_default_ipv4.address != postgres_master"
