---
- hosts: "{{ hosts_prefix }}-tsuru-postgres-*"
  sudo: yes
  sudo_user: root
  vars_files:
    - "postgres_common_vars.yml"

  pre_tasks:
    - name: "PostgreSQL | Get Postgres Master IP from DNS"
      shell: "dig +short {{ postgres_master_host }}"
      register: postgres_master_ip_from_dig
    - name: "PostgreSQL | Set Postgres Master IP fact"
      set_fact:
        postgres_master_ip: "{{ postgres_master_ip_from_dig.stdout }}"
    - include_vars: postgres_master_vars.yml
      when: "ansible_default_ipv4.address == postgres_master_ip"

  roles:
    - ANXS.postgresql
    - { role: wal_e, when: enable_postgres_log_shipping is defined and enable_postgres_log_shipping }

  post_tasks:
    - include: postgres_master_post.yml
      when: "ansible_default_ipv4.address == postgres_master_ip"
    - include: postgres_standby_post.yml
      when: "ansible_default_ipv4.address != postgres_master_ip"
