# vim:ft=ansible:

- name: aalda.docker-registry
  src: https://github.com/codingbunch/ansible-docker-registry.git
  version: v1.0.6
- name: jdauphant.nginx
  src: https://github.com/jdauphant/ansible-role-nginx.git
  version: v1.3.4
- name: ANXS.postgresql
  src: https://github.com/ANXS/postgresql.git
  version: v1.1.2
- name: greendayonfire.mongodb
  src: https://github.com/UnderGreen/ansible-role-mongodb.git
  version: v1.2.2
- name: Stouts.grafana
  src: https://github.com/Stouts/Stouts.grafana.git
  version: 2.0.1
- name: retr0h.etcd
  src: https://github.com/retr0h/ansible-etcd.git
  version: 9a612f2ab2dfd52a9be329030bb2227c4d582423

# GDS created and maintained playbooks
- name: docker_server
  src: https://github.com/alphagov/ansible-playbook-docker_server.git
  version: v0.1.1
- name: hipache
  src: https://github.com/alphagov/ansible-playbook-hipache.git
  version: v0.1.0
- name: tsuru_api
  src: https://github.com/alphagov/ansible-playbook-tsuru_api.git
  version: v0.1.1
- name: gandalf
  src: https://github.com/alphagov/ansible-playbook-gandalf.git
  version: v0.1.0
- name: wal_e
  src: https://github.com/alphagov/ansible-playbook-wal-e.git
  version: v0.0.4
- name: influxdb
  src: https://github.com/alphagov/ansible-playbook-influxdb.git
  version: v0.0.2
- name: telegraf
  src: https://github.com/alphagov/ansible-playbook-telegraf.git
  version: v0.1.0
- name: vulcand
  src: https://github.com/alphagov/ansible-playbook-vulcand.git
  #version: not pinned because under development

# GDS Forked, pull-request sent upstream awaiting merge.
- name: bennojoy.redis
  src: https://github.com/alphagov/ansible-playbook-redis.git
  version: v0.0.2

