- hosts: "{{ hosts_prefix }}-tsuru-router*"
  sudo: yes
  vars:
    upstream_port: "{{ router_port }}"
    vulcand_sealkey_file: "/etc/vulcand.sealkey"
  vars_files:
    - "ssl_proxy_vars.yml"
  pre_tasks:
    - include: ssl_proxy_pre.yml
    - name: "Router | Include SSL proxy varrs"
      include_vars: ssl_proxy_vars.yml
      when: vulcand is not defined
    - name: "Router | set http to https redirect"
      set_fact:
        nginx_sites:
          default:
          - listen 80
          - return 301 https://$host$request_uri
      when: vulcand is defined
      # FIXME: Remove when `tsuru_repo` is deployed.
    - name: Remove upstream APT repo
      apt_repository: repo='ppa:tsuru/ppa' state=absent
    - name: vulcand | Read or generate seal key
      shell: >
        [ -f {{ vulcand_sealkey_file }} ] &&
        cat {{ vulcand_sealkey_file }} ||
        dd if=/dev/urandom count=32 bs=1 2> /dev/null |
          od -A n -t x1 | tr -d ' \n'
      register: vulcand_sealkey
      run_once: true
      when: vulcand is defined
    - name: vulcand | Write seal key
      copy:
        dest: "{{ vulcand_sealkey_file }}"
        content: "{{ vulcand_sealkey.stdout }}"
        mode: 0600
      when: vulcand is defined
  roles:
    - role: hipache
      tsuru_repo: 'ppa:multicloudpaas/tsuru'
      hipache_listen_port: "{{ router_port }}"
      hipache_listen_address: '127.0.0.1'
      hipache_listen_address6: '::1'
      when: vulcand is not defined
    - role: vulcand
      vulcand_version: 'v0.8.0-beta.3'
      vulcand_args:
        port: "{{ router_port }}"
        apiPort: "{{ router_api_port }}"
        etcd: "http://{{ etcd_host }}:{{ etcd_port }}"
        sealKey: "{{ vulcand_sealkey.stdout }}"
      when: vulcand is defined
    - role: jdauphant.nginx
