- hosts: "{{ hosts_prefix }}-tsuru-router*"
  sudo: yes
  vars:
    upstream_port: "{{ router_port }}"
  vars_files:
    - "ssl_proxy_vars.yml"
  pre_tasks:
    - include: ssl_proxy_pre.yml
      # FIXME: Remove when `tsuru_repo` is deployed.
    - name: Remove upstream APT repo
      apt_repository: repo='ppa:tsuru/ppa' state=absent
  roles:
    - role: hipache
      tsuru_repo: 'ppa:multicloudpaas/tsuru'
      hipache_listen_port: "{{ router_port }}"
      hipache_listen_address: '127.0.0.1'
      hipache_listen_address6: '::1'
    - role: jdauphant.nginx
