# Bring up db tier (redis, mongodb).
- include: registry.yml

- hosts: "{{ hosts_prefix }}-tsuru-db"
  sudo: yes
  vars:
    mongodb_conf_dbpath: "/var/lib/mongodb"
  roles:
    - bennojoy.redis
    - greendayonfire.mongodb

# MongoDB: migrate old /data/db dir to new location
  post_tasks:
    - name: MongoDB | Check /data/db directory
      stat: path=/data/db
      register: mongo_data_db
    - name: MongoDB | Migrate data - stop mongo
      service: name=mongod state=stopped
      when: mongo_data_db.stat.isdir is defined and mongo_data_db.stat.isdir
    - name: MongoDB | Migrate data - prepare destination
      shell: >
        rm -rf {{ mongodb_conf_dbpath }}
      when: mongo_data_db.stat.isdir is defined and mongo_data_db.stat.isdir
    - name: MongoDB | Migrate data - move data dir
      shell: >
        mv /data/db {{ mongodb_conf_dbpath }}
      when: mongo_data_db.stat.isdir is defined and mongo_data_db.stat.isdir
    - name: MongoDB | Migrate data - start mongo
      service: name=mongod state=started
      when: mongo_data_db.stat.isdir is defined and mongo_data_db.stat.isdir

# tsuru core components.
- hosts: "{{ hosts_prefix }}-tsuru-gandalf*"
  sudo: yes
  roles:
    - role: gandalf
      tsuru_api_endpoint: "{{ tsuru_api_internal_url }}"

- include: tsuru_api.yml

- hosts: "{{ hosts_prefix }}-tsuru-gandalf*"
  sudo: yes
  tasks:
    - name: generate tsuru token
      run_once: true
      shell: tsr token
      delegate_to: "{{ tsuru_api_host }}"
      register: tsr_token

    - name: write tsuru token to .bash_profile
      lineinfile:
        state: present
        dest: /home/git/.bash_profile
        regexp: export TSURU_TOKEN=
        line: export TSURU_TOKEN={{ tsr_token.stdout }}

    - name: restart gandalf
      service: name=gandalf-server state=restarted

- hosts: "{{ hosts_prefix }}-tsuru-docker*"
  sudo: yes
  roles:
    - docker_server

- hosts: "{{ hosts_prefix }}-tsuru-docker*"
  serial: 1
  sudo: yes
  post_tasks:
    - name: Register node.
      shell: >
        tsuru-admin docker-node-add --register address=http://{{ ansible_default_ipv4.address }}:{{ docker_port }} pool=default </dev/null
      delegate_to: "{{ tsuru_api_host }}"
    - name: Check docker nodes are in the default pool
      shell: >
        tsuru-admin docker-node-list -f pool=default </dev/null
      delegate_to: "{{ tsuru_api_host }}"
      register: docker_node_list
    - name: Update docker node metadata for default pool
      shell: >
        tsuru-admin docker-node-update http://{{ ansible_default_ipv4.address }}:{{ docker_port }} pool=default </dev/null
      delegate_to: "{{ tsuru_api_host }}"
      when: "not ansible_default_ipv4.address in docker_node_list.stdout"

- include: postgres.yml
- include: elasticsearch.yml
- include: router.yml
- include: influx_grafana.yml
- include: post-install.yml
