---

- hosts: "{{ hosts_prefix }}-tsuru-registry"
  sudo: yes
  vars:
    storage_type: "local"
    registry_port: "{{ docker_registry_port }}"
    use_nginx: true
    use_redis: false
    registry_ssl: false

    # Settings below for when we enable gcs backend
    # storage_type: "gcs"
    #gcs_bucket: "{{ deploy_env }}.registry.storage"
    #gcs_storage_path: "/"
    #gcs_oauth2: false
    #gcs_access_key: "{{ lookup('env', 'GCS_ACCESS_KEY') }}"
    #gcs_secret_key: "{{ lookup('env', 'GCS_SECRET_KEY') }}"
  roles:
    - aalda.docker-registry

- include: common.yml
