# Bring up db tier (redis, mongodb).
- include: registry.yml
- include: tsuru_db.yml

# tsuru core components.
- hosts: "{{ hosts_prefix }}-tsuru-gandalf*"
  sudo: yes
  pre_tasks:
      # FIXME: Remove when `tsuru_repo` is deployed.
    - name: Remove upstream APT repo
      apt_repository: repo='ppa:tsuru/ppa' state=absent
  roles:
    - role: gandalf
      tsuru_repo: 'ppa:multicloudpaas/tsuru'
      tsuru_api_endpoint: "{{ tsuru_api_internal_url }}"

- include: tsuru_api.yml

- hosts: "{{ hosts_prefix }}-tsuru-gandalf*"
  sudo: yes
  vars:
    tsuru_cmd: "tsurud"
  tasks:
    - name: generate tsuru token
      run_once: true
      shell: "{{ tsuru_cmd }} token"
      delegate_to: "{{ tsuru_api_host }}"
      register: tsr_token

    - name: write tsuru token to .bash_profile
      lineinfile:
        state: present
        dest: /home/git/.bash_profile
        regexp: export TSURU_TOKEN=
        line: export TSURU_TOKEN={{ tsr_token.stdout }}

    - name: restart gandalf
      service: name=gandalf-server state=restarted

- include: postgres.yml
- include: elasticsearch.yml
- include: router.yml
- include: influx_grafana.yml
- include: post-install.yml
