---

- hosts: "{{ hosts_prefix }}-tsuru-registry"
  sudo: yes
  vars:
    storage_type: "local"
    registry_port: "{{ docker_registry_port }}"
    use_nginx: true
    use_redis: false
    registry_ssl: false

    storage_type: "gcs"
    gcs_bucket: "{{ deploy_env }}-mcp-registry-storage"
    gcs_storage_path: "/"
    gcs_oauth2: false
    gcs_access_key: "{{ google_cloud_storage_access_key }}"
    gcs_secret_key: "{{ google_cloud_storage_secret_key }}"
  roles:
    - aalda.docker-registry

- include: common.yml
