---

- hosts: "{{ hosts_prefix }}-tsuru-registry*"
  sudo: yes
  vars:
    registry_port: "{{ docker_registry_port }}"
    use_nginx: true
    use_redis: false
    registry_ssl: false

    storage_type: "s3"
    s3_region: "eu-west-1"
    s3_bucket: "{{ deploy_env }}-mcp.registry.storage"
    postgres_backup_s3_bucket: "{{ deploy_env }}-mcp.postgres.backup"
    storage_path: "/"

  roles:
    - aalda.docker-registry

- include: common.yml
