---

- hosts: "{{ hosts_prefix }}-tsuru-registry"
  sudo: yes
  vars:
    storage_type: "local"
    registry_port: "{{ docker_registry_port }}"
    use_nginx: true
    use_redis: false
    registry_ssl: false

    storage_type: "gcs"
    gcs_bucket: "{{ deploy_env }}-mcp-registry-storage"
    gcs_storage_path: "/"
    use_gcs_default_credentials: true
  roles:
    - aalda.docker-registry

- include: common.yml
