---
- hosts: gandalf
  sudo: yes
  sudo_user: root
  roles:
    - bennojoy.redis
    - gandalf

- hosts: hipache
  sudo: yes
  sudo_user: root
  roles:
    - hipache
    - {role: aalda.docker-registry,
        registry_port: "{{ docker_registry_port }}",
        use_redis: false,
        use_ssl: false,
        use_nginx: false}

- hosts: api
  sudo: yes
  sudo_user: root
  roles:
    - greendayonfire.mongodb
    - {role: tsuru_api,
       gandalf_host: "{{ hostvars[groups['gandalf'][0]].external_ip }}",
       hipache_host: "{{ hostvars[groups['hipache'][0]].external_ip }}",
       tags: tsuru_api }

- hosts: gandalf
  sudo: yes
  sudo_user: root
  tasks:
    - name: generate tsuru token
      shell: tsr token
      delegate_to: "{{ hostvars[groups['api'][0]].external_ip }}"
      register: tsr_token

    - name: write tsuru token to .bash_profile
      lineinfile:
        state: present
        dest: /home/git/.bash_profile
        regexp: export TSURU_TOKEN=
        line: export TSURU_TOKEN={{ tsr_token.stdout }}

    - name: restart gandalf
      service: name=gandalf-server state=restarted

- hosts: nodes
  sudo: yes
  sudo_user: root
  roles:
    - docker_server

  post_tasks:
    - name: Register node.
      shell: >
        tsuru-admin docker-node-add --register address=http://{{external_ip}}
      delegate_to: "{{ hostvars[groups['api'][0]].external_ip }}"