---
# Bring up db tier (redis, mongodb).
- hosts: redis-master
  sudo: yes
  roles:
    - bennojoy.redis

- hosts: mongodb
  sudo: yes
  sudo_user: root
  roles:
    - greendayonfire.mongodb

- hosts: docker-registry
  sudo: yes
  roles:
    - aalda.docker-registry

# tsuru core components.
- hosts: gandalf
  sudo: yes
  roles:
    - gandalf

- hosts: hipache
  sudo: yes
  roles:
    - hipache

- hosts: api
  sudo: yes
  roles:
    - role: tsuru_api
      tags: tsuru_api

- hosts: gandalf
  sudo: yes
  tasks:
    - name: generate tsuru token
      run_once: true
      shell: tsr token
      delegate_to: "{{ groups['api'][0] }}"
      register: tsr_token

    - name: write tsuru token to .bash_profile
      lineinfile:
        state: present
        dest: /home/git/.bash_profile
        regexp: export TSURU_TOKEN=
        line: export TSURU_TOKEN={{ tsr_token.stdout }}

    - name: restart gandalf
      service: name=gandalf-server state=restarted

- hosts: nodes
  sudo: yes
  roles:
    - docker_server

  post_tasks:
    - name: Register node.
      shell: >
        tsuru-admin docker-node-add --register address=http://{{ internal_ip }}:{{ docker_port }}
      delegate_to: "{{ groups['api'][0] }}"
