- hosts: "{{ hosts_prefix }}-tsuru-api*"
  sudo: yes
  pre_tasks:
    - include: ssl_proxy_pre.yml
    - name: Remove daily snapshots repo
      apt_repository: repo='ppa:tsuru/snapshots' state=absent
      when: vulcand is undefined
    - name: Remove our private repo
      apt_repository: repo='ppa:multicloudpaas/tsuru' state=absent
      when: vulcand is defined
      # FIXME: Remove when `tsuru_repo` is deployed.
    - name: Remove upstream APT repo
      apt_repository: repo='ppa:tsuru/ppa' state=absent
  vars:
    upstream_port: "{{ api_port }}"
    tsuru_api_url: "{{ tsuru_api_external_url }}"
  vars_files:
    - "ssl_proxy_vars.yml"
  roles:
    - role: tsuru_api
      tsuru_package_latest: true
      tsuru_api_listen_addr: 127.0.0.1
      tsuru_repo: "{% if vulcand is defined %}ppa:tsuru/snapshots{% else %}ppa:multicloudpaas/tsuru{% endif %}"
      tags: tsuru_api
    - role: jdauphant.nginx
  tasks:
    - name: Install httplib2 for Ansible uri module
      apt: name=python-httplib2 state=present

# Run these tasks explicitly on 1st API server as the rest of playbooks (post install) expect it
- hosts: "{{ hosts_prefix }}-tsuru-api-0"
  sudo: yes
  tasks:
    - name: add admin team
      shell: >
        mongo tsuru --eval 'db.teams.update({_id: "admin"}, {_id: "admin"}, {upsert: true})';
      delegate_to: "{{ mongodb_host }}"

    - name: add admin user to admin team
      shell: >
        mongo tsuru --eval "db.teams.update({_id: 'admin'}, {\$addToSet: {users: '{{admin_user}}'}})";
      delegate_to: "{{ mongodb_host }}"

    - name: add admin user
      uri:
        method=POST body_format=json
        body="{\"email\":\"{{ admin_user }}\",\"password\":\"{{ admin_password }}\"}"
        url=http://127.0.0.1:{{ api_port }}/users
        status_code=201,409

    - name: login with the admin user
      uri:
        method=POST body_format=json
        body="{\"password\":\"{{ admin_password }}\"}"
        url=http://127.0.0.1:{{ api_port }}/users/{{ admin_user }}/tokens
        return_content=yes
      register: login_response

    - name: write admin token
      copy: dest=~/.tsuru_token mode=0600 content="{{ (login_response.content|from_json).token }}"
