---
- hosts: "{{ hosts_prefix }}-tsuru-db"
  sudo: yes
  vars:
    mongodb_conf_dbpath: "/opt/data/mongodb"
    redis_db_dir: "/opt/data/redis"
    etcd_interface: eth0
  pre_tasks:
    - name: Add tsuru DB into etcd group
      add_host: name={{ inventory_hostname }} groups=etcd
      when: vulcand is defined and vulcand
  roles:
    - bennojoy.redis
    - greendayonfire.mongodb
    - { role: retr0h.etcd, when: vulcand is defined }

  post_tasks:
    - name: Create /opt/data/redis directory
      file: path=/opt/data/redis state=directory mode=0755 owner=redis group=redis
      notify: "restart redis"

  handlers:
    - name: restart redis
      service: name=redis state=restarted

