---

redis_port: 6379
api_port: 8080

docker_registry_host: "{{ deploy_env }}-docker-registry.{{ domain_name }}"
docker_registry_port: 6000
docker_port: 4243
docker_version: 1.7.0

hipache_host_external_lb: "{{ deploy_env }}-hipache.{{ domain_name }}"

influxdb_database: influxdb
influxdb_user: influxdb
influx_pass: influxdb

gandalf_host_external: "{{ deploy_env }}-gandalf.{{ domain_name }}"
gandalf_port: 8080

mongodb_conf_bind_ip: 0.0.0.0
mongodb_port: 27017

tsuru_api_external_url: https://{{ tsuru_api_external_lb }}:443
tsuru_api_internal_url: https://{{ tsuru_api_internal_lb }}:443

# WAL-E Configuration
enable_postgres_log_shipping: true
postgresql_wal_level: hot_standby
postgresql_archive_mode: off
wal_e_base_backup_disabled: true
postgres_backup_s3_bucket: "{{ deploy_env }}-mcp-postgres-backup"
wal_e_s3_prefix: "s3://{{ postgres_backup_s3_bucket }}/wal-e"
wal_e_pgdata_dir: "/var/lib/postgresql/{{ postgresql_version }}/main/"
postgresql_archive_command: >
  /usr/bin/envdir {{ wal_e_envdir }} /usr/local/bin/wal-e
  {% if wal_e_aws_instance_profile %}--aws-instance-profile{% endif %} wal-push %p
