---

redis_host_name: "{{ deploy_env }}-tsuru-db"
redis_host: "{{ hostvars[redis_host_name]['gce_private_ip'] }}"
redis_port: 6379

tsuru_api_name: "{{ deploy_env }}-tsuru-api-0"
tsuru_api_internal_lb: "{{ hostvars[tsuru_api_name]['gce_private_ip'] }}"
api_port: 8080

docker_registry_name: "{{ deploy_env }}-tsuru-registry"
docker_registry_host: "{{ hostvars[docker_registry_name]['gce_private_ip'] }}"
docker_registry_port: 6000
docker_port: 4243

hipache_host_name: "{{ deploy_env }}-tsuru-api-1"
hipache_host_external_lb: "{{ deploy_env }}-hipache.{{ domain_name }}"
hipache_host_internal_lb: "{{ deploy_env }}-hipache.{{ domain_name }}"

gandalf_host_name: "{{ deploy_env }}-tsuru-gandalf"
gandalf_host_internal: "{{ hostvars[gandalf_host_name]['gce_private_ip'] }}"
gandalf_host_external: "{{ deploy_env }}-gandalf.{{ domain_name }}"
gandalf_port: 8080

mongodb_host_name: "{{ deploy_env }}-tsuru-db"
mongodb_conf_bind_ip: 0.0.0.0
mongodb_host: "{{ hostvars[mongodb_host_name]['gce_private_ip'] }}"
mongodb_port: 27017
